import { BrainRecord, BrainRelationship } from '../types/missionControl';

export const BRAIN_STATUSES = [
  "discovered", "registered", "connected", "disconnected",
  "busy", "idle", "executing",
  "healthy", "unhealthy", "degraded", "failed",
  "removed", "paused", "resumed", "restarting", "shutdown", "recovering",
] as const;

export const BRAIN_TYPES = ["local_cli", "cloud_api", "orchestrator", "mcp_server", "custom"] as const;

export const BRAIN_VENDORS = [
  "openai", "anthropic", "google", "mistral", "groq", "azure", "aws", "vertex",
  "openrouter", "cohere", "deepseek", "qwen", "moonshot", "together", "fireworks",
  "replicate", "ollama", "lm_studio", "vllm", "hermes", "claude_code", "gemini_cli",
  "codex", "opencode", "aider", "continue", "github_copilot", "cursor", "custom",
] as const;

export const BRAIN_RUNTIMES = [
  "python", "node", "go", "rust", "container", "native", "cloud", "unknown", "bun", "deno",
] as const;

export const VENDOR_COLORS: Record<string, string> = {
  openai: '#10a37f',
  anthropic: '#d980ff',
  google: '#4285f4',
  deepseek: '#4f6bff',
  mistral: '#ff9900',
  groq: '#f97316',
  openrouter: '#8b5cf6',
  ollama: '#f97316',
  hermes: '#00f0ff',
  claude_code: '#d980ff',
  gemini_cli: '#4285f4',
  codex: '#818cf8',
  python: '#38bdf8',
  node: '#22c55e',
  git: '#f05032',
  custom: '#a855f7',
};

export const VENDOR_ICON_MAP = VENDOR_COLORS;

export const VENDOR_NAMES: Record<string, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  google: 'Google Cloud',
  deepseek: 'DeepSeek AI',
  mistral: 'Mistral AI',
  groq: 'Groq LPU',
  openrouter: 'OpenRouter',
  ollama: 'Ollama Local',
  hermes: 'Hermes Agent',
  claude_code: 'Claude Code CLI',
  gemini_cli: 'Gemini CLI',
  codex: 'OpenAI Codex',
  custom: 'System Runtime',
};

export function getVendorColor(vendor: string): string {
  const low = vendor.toLowerCase();
  for (const [k, color] of Object.entries(VENDOR_COLORS)) {
    if (low.includes(k)) return color;
  }
  return '#00f0ff';
}

export function brainStatusToColor(status: string): string {
  const map: Record<string, string> = {
    discovered: '#6366f1',
    registered: '#22d3ee',
    connected: '#22c55e',
    disconnected: '#94a3b8',
    busy: '#f59e0b',
    idle: '#38bdf8',
    executing: '#10b981',
    healthy: '#10b981',
    unhealthy: '#ef4444',
    degraded: '#f97316',
    failed: '#ef4444',
    paused: '#f59e0b',
    restarting: '#818cf8',
  };
  return map[status] || '#38bdf8';
}

export const INITIAL_BRAINS: BrainRecord[] = [
  {
    id: '4624bdfc7932',
    display_name: 'Python 3.10 Kernel',
    brain_type: 'orchestrator',
    vendor: 'custom',
    runtime: 'python',
    version: '3.10.12',
    status: 'connected',
    health: 'healthy',
    capabilities: ['code_generation', 'testing', 'reasoning', 'file_operations', 'asyncio_kernel', 'fastapi_api'],
    supported_models: ['cpython-v3.10', 'bytecode-ast'],
    supported_tools: ['pytest', 'pip', 'uvicorn', 'agentic_os_cli'],
    memory_usage: 103.2,
    cpu_usage: 2.1,
    latency: 5,
    throughput: 240,
    workspace: '/app/applet/AgenticosHybrid',
    current_tasks: 2,
    queue_depth: 0,
    active_models: 4,
    available_context: 512000,
    connection_state: 'connected',
    uptime: 3840,
    heartbeat: new Date().toISOString(),
    tags: ['kernel', 'orchestrator', 'fastapi', 'core-engine'],
    priority: 10,
    metadata: { executable: '/usr/bin/python3', isolated: false, di_container: 'container.py:v2' },
    discovered_at: '2026-09-16T08:59:30Z',
    last_seen: new Date().toISOString(),
    session_count: 86,
    error_count: 0,
    last_error: null,
  },
  {
    id: '682e1c85c0a1',
    display_name: 'Node v22 Runtime',
    brain_type: 'local_cli',
    vendor: 'custom',
    runtime: 'node',
    version: '22.23.2',
    status: 'idle',
    health: 'healthy',
    capabilities: ['code_generation', 'testing', 'javascript', 'typescript', 'vite_server'],
    supported_models: ['v8-turbo', 'esm-loader'],
    supported_tools: ['node', 'npm', 'npx', 'tsc'],
    memory_usage: 112.4,
    cpu_usage: 1.4,
    latency: 8,
    throughput: 120,
    workspace: '/app/applet',
    current_tasks: 1,
    queue_depth: 0,
    active_models: 2,
    available_context: 256000,
    connection_state: 'connected',
    uptime: 3840,
    heartbeat: new Date().toISOString(),
    tags: ['runtime', 'javascript', 'frontend-bridge'],
    priority: 8,
    metadata: { executable: '/usr/local/bin/node', isolated: false },
    discovered_at: '2026-09-16T08:59:30Z',
    last_seen: new Date().toISOString(),
    session_count: 48,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'a96ace66a30a',
    display_name: 'Git Version Controller',
    brain_type: 'local_cli',
    vendor: 'custom',
    runtime: 'unknown',
    version: '2.34.1',
    status: 'idle',
    health: 'healthy',
    capabilities: ['file_operations', 'version_control', 'diff_analysis', 'branch_graph'],
    supported_models: ['git-core'],
    supported_tools: ['git status', 'git diff', 'git commit', 'git log'],
    memory_usage: 42.5,
    cpu_usage: 0.5,
    latency: 12,
    throughput: 85,
    workspace: '/app/applet/AgenticosHybrid',
    current_tasks: 0,
    queue_depth: 0,
    active_models: 1,
    available_context: 128000,
    connection_state: 'connected',
    uptime: 3840,
    heartbeat: new Date().toISOString(),
    tags: ['vcs', 'git', 'cli-tool'],
    priority: 7,
    metadata: { executable: '/usr/bin/git', isolated: true },
    discovered_at: '2026-09-16T08:59:30Z',
    last_seen: new Date().toISOString(),
    session_count: 14,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'brain-claude-37',
    display_name: 'Claude 3.7 Sonnet (Hybrid)',
    brain_type: 'cloud_api',
    vendor: 'anthropic',
    runtime: 'cloud',
    version: 'claude-3-7-sonnet-20250219',
    status: 'connected',
    health: 'healthy',
    capabilities: ['extended_thinking', 'code_generation', 'deep_reasoning', 'architecture_audit', 'tool_use'],
    supported_models: ['claude-3-7-sonnet-thinking', 'claude-3-5-haiku'],
    supported_tools: ['bash', 'edit_file', 'grep_search', 'web_search'],
    memory_usage: 68.0,
    cpu_usage: 1.1,
    latency: 24,
    throughput: 65,
    workspace: 'cloud://api.anthropic.com/v1',
    current_tasks: 1,
    queue_depth: 0,
    active_models: 2,
    available_context: 200000,
    connection_state: 'connected',
    uptime: 7200,
    heartbeat: new Date().toISOString(),
    tags: ['cloud-llm', 'reasoning', 'thinking-model'],
    priority: 9,
    metadata: { provider: 'Anthropic', streaming: true, function_calling: true },
    discovered_at: '2026-09-16T08:30:00Z',
    last_seen: new Date().toISOString(),
    session_count: 124,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'brain-gemini-25',
    display_name: 'Gemini 2.5 Flash',
    brain_type: 'cloud_api',
    vendor: 'google',
    runtime: 'cloud',
    version: 'gemini-2.5-flash-preview',
    status: 'connected',
    health: 'healthy',
    capabilities: ['multimodal', 'high_throughput', 'audio_stream', 'code_synthesis', 'grounding'],
    supported_models: ['gemini-2.5-flash', 'gemini-2.5-pro'],
    supported_tools: ['google_search', 'code_execution', 'url_retrieval'],
    memory_usage: 52.0,
    cpu_usage: 0.9,
    latency: 18,
    throughput: 180,
    workspace: 'cloud://generativelanguage.googleapis.com',
    current_tasks: 0,
    queue_depth: 0,
    active_models: 2,
    available_context: 1048576,
    connection_state: 'connected',
    uptime: 7200,
    heartbeat: new Date().toISOString(),
    tags: ['google-genai', 'fast-flash', 'multimodal'],
    priority: 9,
    metadata: { provider: 'Google AI Studio', context_tokens: 1048576 },
    discovered_at: '2026-09-16T08:30:00Z',
    last_seen: new Date().toISOString(),
    session_count: 98,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'brain-deepseek-r1',
    display_name: 'DeepSeek R1 (Reasoner)',
    brain_type: 'cloud_api',
    vendor: 'deepseek',
    runtime: 'cloud',
    version: 'deepseek-reasoner-v1',
    status: 'connected',
    health: 'healthy',
    capabilities: ['mathematical_proof', 'algorithmic_optimization', 'code_verification'],
    supported_models: ['deepseek-r1', 'deepseek-v3'],
    supported_tools: ['code_eval', 'logic_prover'],
    memory_usage: 58.0,
    cpu_usage: 1.2,
    latency: 35,
    throughput: 42,
    workspace: 'cloud://api.deepseek.com',
    current_tasks: 0,
    queue_depth: 0,
    active_models: 1,
    available_context: 64000,
    connection_state: 'connected',
    uptime: 5400,
    heartbeat: new Date().toISOString(),
    tags: ['deepseek', 'reasoner', 'math-logic'],
    priority: 8,
    metadata: { provider: 'DeepSeek API', reasoning_tokens: true },
    discovered_at: '2026-09-16T08:35:00Z',
    last_seen: new Date().toISOString(),
    session_count: 42,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'brain-ollama-llama3',
    display_name: 'Ollama Llama 3.3 70B',
    brain_type: 'local_cli',
    vendor: 'ollama',
    runtime: 'container',
    version: 'llama3.3:70b-instruct-q4_K_M',
    status: 'idle',
    health: 'healthy',
    capabilities: ['offline_inference', 'privacy_safe', 'code_explanation', 'local_embedding'],
    supported_models: ['llama3.3:70b', 'nomic-embed-text'],
    supported_tools: ['ollama_run', 'ollama_embeddings'],
    memory_usage: 240.0,
    cpu_usage: 4.5,
    latency: 48,
    throughput: 32,
    workspace: 'http://localhost:11434',
    current_tasks: 0,
    queue_depth: 0,
    active_models: 1,
    available_context: 128000,
    connection_state: 'connected',
    uptime: 2100,
    heartbeat: new Date().toISOString(),
    tags: ['local-llm', 'privacy', 'gpu-accelerated'],
    priority: 7,
    metadata: { quantization: 'Q4_K_M', context_window: 128000 },
    discovered_at: '2026-09-16T09:10:00Z',
    last_seen: new Date().toISOString(),
    session_count: 18,
    error_count: 0,
    last_error: null,
  },
  {
    id: 'brain-hermes-agent',
    display_name: 'Hermes 3 Function Brain',
    brain_type: 'orchestrator',
    vendor: 'hermes',
    runtime: 'python',
    version: 'hermes-3-llama-3.1-405b',
    status: 'connected',
    health: 'healthy',
    capabilities: ['json_mode', 'structured_outputs', 'agent_debate', 'tool_calling_eval'],
    supported_models: ['hermes-3-405b', 'hermes-3-70b'],
    supported_tools: ['hermes_planner', 'function_caller'],
    memory_usage: 74.0,
    cpu_usage: 1.6,
    latency: 28,
    throughput: 55,
    workspace: 'agenticos://hermes/agent',
    current_tasks: 1,
    queue_depth: 0,
    active_models: 2,
    available_context: 131072,
    connection_state: 'connected',
    uptime: 4200,
    heartbeat: new Date().toISOString(),
    tags: ['autonomous-agent', 'hermes', 'tool-caller'],
    priority: 8,
    metadata: { framework: 'Nous Research Hermes', temperature: 0.2 },
    discovered_at: '2026-09-16T09:00:00Z',
    last_seen: new Date().toISOString(),
    session_count: 67,
    error_count: 0,
    last_error: null,
  }
];

export const INITIAL_RELATIONSHIPS: BrainRelationship[] = [
  {
    id: 'rel-py-git',
    source_id: '4624bdfc7932',
    target_id: 'a96ace66a30a',
    relationship_type: 'tool_usage',
    weight: 0.9,
    active: true,
  },
  {
    id: 'rel-py-node',
    source_id: '4624bdfc7932',
    target_id: '682e1c85c0a1',
    relationship_type: 'peer',
    weight: 0.85,
    active: true,
  },
  {
    id: 'rel-py-claude',
    source_id: '4624bdfc7932',
    target_id: 'brain-claude-37',
    relationship_type: 'delegation',
    weight: 0.95,
    active: true,
  },
  {
    id: 'rel-py-gemini',
    source_id: '4624bdfc7932',
    target_id: 'brain-gemini-25',
    relationship_type: 'delegation',
    weight: 0.92,
    active: true,
  },
  {
    id: 'rel-py-deepseek',
    source_id: '4624bdfc7932',
    target_id: 'brain-deepseek-r1',
    relationship_type: 'reviewer',
    weight: 0.88,
    active: true,
  },
  {
    id: 'rel-claude-hermes',
    source_id: 'brain-claude-37',
    target_id: 'brain-hermes-agent',
    relationship_type: 'consensus',
    weight: 0.82,
    active: true,
  },
  {
    id: 'rel-py-ollama',
    source_id: '4624bdfc7932',
    target_id: 'brain-ollama-llama3',
    relationship_type: 'fallback',
    weight: 0.75,
    active: true,
  },
];
